### ISSUE TITLE
--workers 12 seems to be a no-op

### ISSUE THREAD

**Issue by sshleifer** [pgjones/hypercorn#100]
Hi, I migrated our flask app to Quart + hypercorn last week, and am having trouble experimenting with using multiple processes (`--workers 12`). More specifically, passing `--workers 12` causes 12 print statements but no change in `ps aux | grep hypercorn`  -- still 3 pids.  Is there a way to have 12 processes, each using N async threads running my app? 

My end goal is to improve performance against baseline `flask.run(threaded=True)`, but at the moment I am slightly behind.

Thanks in advance!

### Code

Launch Command:
```
hypercorn  'example:app' --access-logfile=-  -b 0.0.0.0:7395 -k uvloop --workers 12
```

#### Example.py
<details>

```python
from redis import asyncio as redis
from quart import Quart, request, Response
REDIS_URL = "redis://127.0.0.1:6379"

app = Quart(__name__, static_url_path="")
tokenizer = build_tokenizer() 
redis_client = redis.Redis(auto_close_connection_pool=False, decode_responses=True)
# Redis PubSub utils
async def publish_payload(channel_name, payload):
    r = redis.from_url(REDIS_URL)
    await r.publish(channel_name, payload)

async def read_channel(channel_name):
    r = redis.from_url(REDIS_URL)
    async with r.pubsub() as pubsub:
        await pubsub.subscribe(channel_name)
        while True:
            message = await pubsub.get_message(ignore_subscribe_messages=True)
            if message is not None:
                data = json.loads(message["data"].decode())
                yield data
                if data[0]["is_final"]:
                    break

@app.route("/generate", methods=["PUT"])
async def generate():
     request_id = generate_uuid()
     publish_payload('requests',  request)
     iterable_to_return = read_channel(request_id)  # no await type:async_generator
     return Response(iterable_to_return)
```

</details>

**Comment by pgjones** [comment]
I'm not sure what is going on here. The 12 print statements indicate that 12 workers have started, so I'd expect there to be 12 processes (actually 13 as there is one main process). What does the process tree look like whilst it is running?
