### ISSUE TITLE
App import happening twice

### ISSUE THREAD

**Issue by dacevedo12** [pgjones/hypercorn#101]
In large apps hypercorn is slow to initialize as it performs duplicate work loading the provided app.

I've narrowed it down to these calls:

- https://github.com/pgjones/hypercorn/blob/main/src/hypercorn/run.py#L42
- https://github.com/pgjones/hypercorn/blob/main/src/hypercorn/asyncio/run.py#L205

**Comment by pgjones** [comment]
I think #143 resolves this, please reopen if not.
