### ISSUE TITLE
read_timeout crashes hypercorn on trio

### ISSUE THREAD

**Issue by richardsheridan** [pgjones/hypercorn#103]
If read_timeout is triggered on the trio backend, hypercorn exits with a `trio.TooSlowError`.  This is caused by the use of `trio.fail_after`:

https://github.com/pgjones/hypercorn/blob/8ae17ca68204d9718389fb3649ca0ed6ba851906/src/hypercorn/trio/tcp_server.py#L94-L105

Comparing the same code on asyncio backend, asyncio handles timeout exceptions and closes the protocol:

https://github.com/pgjones/hypercorn/blob/8ae17ca68204d9718389fb3649ca0ed6ba851906/src/hypercorn/asyncio/tcp_server.py#L93-L107

handling `trio.TooSlowError` in that same block seems to work but I'm not totally sure what the correct behavior is "supposed" to be.

**Comment by pgjones** [comment]
Should be fixed in main
