### ISSUE TITLE
Issue since 0.14.2

### ISSUE THREAD

**Issue by jrlopes2005** [pgjones/hypercorn#109]
HI.

SInce hypercorn version 0.14.2, my code breaks when using dependency injection from inject library (https://github.com/ivankorobkov/python-inject).

The only change in my code was the update of hypercorn version. I apply the bindings of interfaces to implementations before hypercorn runs.

How this update can affect other python packages/libraries?

**Comment by albertoreis86** [comment]
Same problem here, although for me breaks above 0.13.2.
Running on MacOs with 2,6 GHz 6-Core Intel Core i7

**Comment by pgjones** [comment]
I will need more information to be able to help. What actually breaks? Is there a stack trace? What are you trying to inject and could it be a problem with the inject library instead?

Please reopen if you can supply this information.
