### ISSUE TITLE
Quartz + Hypercorn(0.14) application does not execute @app.before_serving decorator

### ISSUE THREAD

**Issue by jpchang-episci** [pgjones/hypercorn#115]
I have python 3.8 (quartz 0.17 + hypercorn 0.11) and I am in progress of upgrading to python 3.11.  I noticed that @app.before_serving will not execute when it bootstraps.  I had made it (python 3.11) wokring with hypercorn 0.12.

**Comment by pgjones** [comment]
This works for me, please reopen with more information if it still doesn't work.
