### ISSUE TITLE
A "while_serving" decorator?

### ISSUE THREAD

**Issue by jonozzz** [pgjones/hypercorn#13]
What do you think about having another decorator like this that would allow you to control when server is shut down

This is useful when you need a server up for to X seconds, rather than forever. I think you could spin up a thread with a timer and have that call loop.stop() when done, but it's dirty.

```
@app.while_serving
async def shutdown_when_idle_for_seconds():
    while True:
        if condition:
            raise Shutdown
        await sleep(1)
```
Great for testing!

**Comment by jonozzz** [comment]
I need to programmatically spin up a sever and a client to test an external load balancer. Having a server that runs forever is not really an option.

**Comment by pgjones** [comment]
Could you do something like this?
```python
def shutdown():
    raise Shutdown()  # Or maybe sys.exit?

loop = asyncio.get_event_loop()
loop.call_later(1, shutdown)
loop.run_until_complete(serve(app, config)
```

I'm not sure this is a common enough use case to be part of Hypercorn.

**Comment by jonozzz** [comment]
One issue with that might be that "serve" would want to call run_forever at some point which is not possible, since the loop is already running.

I don't think it'd be too complicated to add, I see it as an addition to the "before_serving" and "after_serving" decorators.

**Comment by pgjones** [comment]
I this case `serve` is a coroutine, 1ecfcc3ac8a1da1b8b12efdd5cab51fd41ad1c2f so the run_until_complete shouldn't be an issue.

> I see it as an addition to the "before_serving" and "after_serving" decorators.

So when would it be called? Some options I can think of are, after the first request, after every request, periodically (what period).

**Comment by jonozzz** [comment]
Is this `serve()` in the latest hypercorn version only compatible with quart 0.7.x? I can't make it work with quart 0.6 version on python 3.6.

**Comment by pgjones** [comment]
It should work with 0.6 on Python 3.6, what is the error you are getting? (I've not released it yet though).

**Comment by jonozzz** [comment]
Here's an update... Enabled some error logging and got:
`ASGI Framework Lifespan error, continuing without Lifespan support`

Quart 0.6 doesn't seem to have the `"lifespan"` scope type.

**Comment by pgjones** [comment]
I see, it was a race condition - I've fixed it in 16b0ae8f898e641a4c3d565f2a2f01ea9cedda61 could you see if it works for you?

**Comment by jonozzz** [comment]
Works now!
Back to my initial ask, I poked around the code a bit and noticed that you have a `shutdown_event` argument that I could use, but it doesn't bubble up to `serve()`. Any reason why it doesn't?
https://github.com/pgjones/hypercorn/blob/master/hypercorn/asyncio/run.py#L128

Also, would it make sense to have a similar `startup_event` or something like that, that's set when the server is ready to take new connections?

**Comment by pgjones** [comment]
I think your use case might be too specific for Hypercorn to support directly, I think the before/after serving functionality should cover almost all use. I'm actually not sure how it doesn't cover your case (I think it should).

**Comment by jonozzz** [comment]
But would it make sense to expose `shutdown_event` kwarg to `serve` coro?

**Comment by pgjones** [comment]
I don't think so as I'd like to keep the public API as simple as possible. You could use the `worker_serve` coro though (basically serve with the shutdown_event).

**Comment by pgjones** [comment]
Closing for now
