### ISSUE TITLE
Guide on deploying to cloud providers

### ISSUE THREAD

**Issue by yaoshiang** [pgjones/hypercorn#132]
A useful guide would be deployment to AWS, GCP, Azure, etc., mentioning specific services. It might be the case that hyper corn is really meant to be deployed as a docker container / Kubernetes cluster, or maybe it's possible to use hypercorn with AWS Lambda or AWS Elastic Beanstalk. 

A guide like this would be helpful for folks who've developed an app in dev environment and now want to push it live.

**Comment by pgjones** [comment]
There really isn't anything special or specific - Hypercorn is great in any deployment where you'd bind to a host & port. 

For AWS Lambda try [mangum](https://github.com/jordaneremieff/mangum).
