### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [pgjones/hypercorn#138]
Is it possible next time on release new version make the github release to have entry on https://github.com/pgjones/hypercorn/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by njsmith** [comment]
@pgjones Fyi in case you don't recognize their name: this person has been
making a nuisance of themselves for months and months across tons of
projects, all with these kind of weird time wasting requests. I'd probably
just block them tbh.

**Comment by kloczek** [comment]
Explanation: I have automation process those notification trying make preliminary automated upgrade of building packages which allow save some time on maintaining packaging procedures.
Many maintainers see some values of spreading such notifications for other reasons as well like to ask to test anyone interested to test ASP new version providing kind of confirmation that new version is OK.
If some maintainers don't see such added values nothing bad will happen/no one will cry.
