### ISSUE TITLE
Error loading "client" from "REMOTE_ADDR"

### ISSUE THREAD

**Issue by lunoho** [pgjones/hypercorn#139]
Running Hypercorn via NGINX proxy:

```
    location / {
        include proxy_params;
        proxy_pass http://unix:/tmp/hypercorn.sock;
    }
```

Receiving the following error:

```
Traceback (most recent call last):
  File ".../.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File ".../.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 50, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File ".../.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 78, in handle_http
    environ = _build_environ(scope, body)
  File ".../.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 136, in _build_environ
    environ["REMOTE_ADDR"] = scope["client"][0]
TypeError: 'NoneType' object is not subscriptable
```

This is the contents of the scope dictionary:
`{'type': 'http', 'http_version': '1.0', 'asgi': {'spec_version': '2.1', 'version': '3.0'}, 'method': 'GET', 'scheme': 'http', 'path': '/', 'raw_path': b'/', 'query_string': b'', 'root_path': '', 'headers': [(b'host', <redacted>'), (b'x-real-ip', b'216.147.123.78'), (b'x-forwarded-for', b'<redacted>'), (b'x-forwarded-proto', b'https'), (b'x-real-ip', b'<redacted>'), (b'connection', b'close'), (b'accept', b'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), (b'sec-fetch-site', b'none'), (b'accept-encoding', b'gzip, deflate, br'), (b'sec-fetch-mode', b'navigate'), (b'user-agent', b'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15'), (b'accept-language', b'en-US,en;q=0.9'), (b'sec-fetch-dest', b'document')], 'client': None, 'server': None, 'extensions': {}}`

I have made a temp fix to my version of app_wrapper.py with the following change to line 136:

`    if "client" in scope and scope['client'] is not None:`

Thanks for reviewing this!

**Comment by pgjones** [comment]
Fixed in 30e6f03a11a138280bde4dc7ec66c668242c87c6
