### ISSUE TITLE
Hypercorn 0.5.0 does not provide the extra 'asyncio'

### ISSUE THREAD

**Issue by Allandor** [pgjones/hypercorn#14]
I try to install the asyncio Worker via pip.

Collecting Hypercorn[asyncio] (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/94/69/f9c42534223b1d5bf0928a4ba7ea3ffe8f5a89da8cf967e781d550ea144b/Hypercorn-0.5.0-py3-none-any.whl (42kB)
  Hypercorn 0.5.0 does not provide the extra 'asyncio'

Could youe re add the dependency?

Thanks.

**Comment by pgjones** [comment]
asyncio is part of the Python standard library, so there is no need to install any extras.

**Comment by Allandor** [comment]
Hi, thanks now its working. Before i got the error that no asyncio worker was avaiable.
