### ISSUE TITLE
HTTP/2 Rapid Reset

### ISSUE THREAD

**Issue by RinnDog** [pgjones/hypercorn#146]
Has any patches to HTTP/2 CVE been released?
https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/

**Comment by synodriver** [comment]
I suggest look into [this function](https://github.com/pgjones/hypercorn/blob/main/src/hypercorn/protocol/h2.py#L236) to see if sans-io based protocol parser actually handles this issue.

**Comment by pgjones** [comment]
I think the correct fix is to apply a max keep alive requests. I have a patch being tested locally.

Note though I don't think Hypercorn itself is that vulnerable as resetting streams quickly isn't likely to be that costly.

**Comment by pgjones** [comment]
Mitigation in 926c4303a7298ce53a772cf6cec9a3da75be35a2
