### ISSUE TITLE
Fails to load cert chain when using signed certificates

### ISSUE THREAD

**Issue by tjtaill** [pgjones/hypercorn#15]
Hi I believe there is bug at 

https://github.com/pgjones/hypercorn/blob/master/hypercorn/config.py#L158

when I use quart with signed certificate in quart as follows
 
app.run(ca_certs='ca.crt', certfile='cert.crt', kefile='key.pem')

I get the following

hypercorn/config.py", line 158, in create_ssl_context
    context.load_cert_chain(certfile=self.certfile, keyfile=self.keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3824)

I believe line https://github.com/pgjones/hypercorn/blob/master/hypercorn/config.py#L160
should be called before 

https://github.com/pgjones/hypercorn/blob/master/hypercorn/config.py#L158

anyways I have reverted to unsigned certs for now and will probably just use gunicorn
but I thought I would let you know about this bug and thank you for your quart project
which I am really loving

**Comment by pgjones** [comment]
Thanks, I've not seen this before, could you try this patch?
```patch
diff --git a/hypercorn/config.py b/hypercorn/config.py
index 1ebf116..61f8bce 100644
--- a/hypercorn/config.py
+++ b/hypercorn/config.py
@@ -155,13 +155,13 @@ class Config:
         except NotImplementedError:
             pass  # NPN is not necessarily available
 
-        context.load_cert_chain(certfile=self.certfile, keyfile=self.keyfile)
-        if self.ca_certs is not None:
-            context.load_verify_locations(self.ca_certs)
         if self.verify_mode is not None:
             context.verify_mode = self.verify_mode
         if self.verify_flags is not None:
             context.verify_flags = self.verify_flags
+        if self.ca_certs is not None:
+            context.load_verify_locations(self.ca_certs)
+        context.load_cert_chain(certfile=self.certfile, keyfile=self.keyfile)
 
         return context
```

**Comment by tjtaill** [comment]
I will try the patch sorry been busy learning azure

**Comment by tjtaill** [comment]
sorry I think there is something wrong with my own ca cert it is not in proper PEM format the way to check this is with the following command

openssl x509 -in ca.crt -text -noout (if it fails then not PEM)

I will keep you updated if this works or you can close this issue if you want

**Comment by tjtaill** [comment]
I tried you patch it didn't work unfortunately. Tried a couple of other things as well like loading the cafile in the creation of the ssl context that didn't work either. There might be something wrong with my certificates I will try with gunicorn and let you know if I had success there.

**Comment by pgjones** [comment]
Hmm, this is weird. Please update with what you find.

**Comment by tjtaill** [comment]
Ok sorry I took so long in the end there is nothing wrong with hypercorn's code I have it working fine
it was just very complicated to figure out how to setup the certificate chain so that it would be trusted is all. There was a bug in the key file generated by the provider as well.

**Comment by pgjones** [comment]
Do the hypercorn docs on SSL setup need improving, or was the complication outside of hypercorn?

**Comment by tjtaill** [comment]
> Do the hypercorn docs on SSL setup need improving, or was the complication outside of hypercorn?

The complication is from python SSL, you need to `pip install certifi` to get the CA file you need, and that setup your certfile file in following format

certificate
intermediate certificates
root certificate

they have to be in the correct order and the root certificate has to be in the ca file as well

here is my hypercorn python config file I use

```python
import certifi

bind = ['0.0.0.0:443']
ca_certs = certifi.where()
certfile = 'cert_prod.pem'
keyfile = 'key_prod.pem'
```

go daddy also gave me a corrupted key file so I needed to debug that as well
