### ISSUE TITLE
Reload breaks from 0.14.4 to 0.15.0

### ISSUE THREAD

**Issue by Rash-in** [pgjones/hypercorn#151]
When using the --reload option on command line I am getting an error in 0.15.0 wheras I am not getting an error in 0.14.4. I save a watched file with no changes to it and the error appears: `OSError: [Errno 48] Address already in use` and the app dies.

Command am using in both places (with generic substitutions):

`'cd /path/to/app && export APP_PATH=/path/to/app && export PYTHONDONTWRITEBYTECODE="true" && . .env/bin/activate && hypercorn --bind "0.0.0.0:5000" --worker-class "asyncio" --log-level "DEBUG" --error-logfile "-" --reload `

After a bit of research in [run.py](https://github.com/pgjones/hypercorn/blob/19dfb96411575a6a647cdea63fa581b48ebb9180/src/hypercorn/run.py#L77):
The lastest tag has `sockets = config.create_sockets()` If I revert back to 0.14.4 and re-add that line, i can reproduce the error.

**Comment by lemur117** [comment]
I'm experiencing the same issue, also with the transition from 0.14.4 to 0.15.0.  Here is the traceback from my environment:

```
  File "/app/venv/bin/hypercorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/venv/lib/python3.12/site-packages/hypercorn/__main__.py", line 287, in main
    run(config)
  File "/app/venv/lib/python3.12/site-packages/hypercorn/run.py", line 77, in run
    sockets = config.create_sockets()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/hypercorn/config.py", line 197, in create_sockets
    secure_sockets = self._create_sockets(self.bind)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/hypercorn/config.py", line 266, in _create_sockets
    sock.bind(binding)
OSError: [Errno 98] Address already in use

```

**Comment by Rash-in** [comment]
I managed to find a fix in [code](https://github.com/pgjones/hypercorn/blob/19dfb96411575a6a647cdea63fa581b48ebb9180/src/hypercorn/config.py#L246) that would alleviate the issue, although not sure if it would break something else (first contribution to OSS so be easy on me).

on line 246 of config.py
editing the line to `if self.workers > 1 or self.use_reloader:`

this would try to reuse the existing binds to create a new socket.

@pgjones, is this something that would be easy to test out?

**Comment by mrchoke** [comment]
Confirmed!!

**Comment by lemur117** [comment]
The fix on line 246 of config.py appears to work for me also.  Thanks for sharing!

**Comment by waiyan13** [comment]
Any update on this issue? Is there going to be a fix?

**Comment by pgjones** [comment]
Reverted breaking change in https://github.com/pgjones/hypercorn/commit/ebb09a6c606c2a9c4e6e3a2d4c7a27262cdf6573
