### ISSUE TITLE
--reload not working with Quart

### ISSUE THREAD

**Issue by McSpidey** [pgjones/hypercorn#16]
I've been trying to get Hypercorn + Quart autoreloading on code change working and think I've found a bug.

The Hypercorn usage doc suggests the correct flag is "--reload"
https://github.com/pgjones/hypercorn/blob/master/docs/usage.rst

When I use this it starts fine but the moment I edit the Quart source code file and save it Hypercorn crashes with this error:
"unknown option --reload"

I've checked the Quart docs (https://pgjones.gitlab.io/quart/source/quart.app.html
) and it suggests the internal flag may be "use_reloader", however if I try that with Hypercorn it doesn't start, giving this error.
"hypercorn: error: unrecognized arguments: --use_reloader"

In case it was a mismatch between versions I just tried uninstalling and re-installing both Quart and Hypercorn but there was no change. What's the best way to go about this?

**Comment by pgjones** [comment]
Could you show the full command you use with `--reload` and the error trace that goes with it?

**Comment by McSpidey** [comment]
Unfortunately there is no trace. Here's the full message.

-
C:\Users\xxx\Dropbox\Python\yyy\Console>hypercorn --reload -w 1 -b 0.0.0.0:80 app:app
Running on 0.0.0.0:80 over http (CTRL + C to quit)
unknown option --reload
usage: c:\users\xxx\.virtualenvs\console-pphxaxy4\scripts\python.exe [option] ... [-c cmd |
-C:\Users\xxx\Dropbox\Python\yyy\Console>m mod | file | -] [arg] ...
Try `python -h' for more information.
-

I'm using a virtual env, in this case pipenv, and looking at that error it seems the --reload flag is attempting to be interpreted by Python.exe and being rejected.

**Comment by pgjones** [comment]
I think I fixed this in bb6989da48080478a87d4e909b3da00fe6fe6ca4, could you try that?

**Comment by McSpidey** [comment]
Confirmed, when I edit that line into my local copy of that file it works. Nice job!

**Comment by marodev** [comment]
@McSpidey May I ask you to try it with multiple workers? Is this supported on Windows?

for example:

`hypercorn  -w 2 -b 0.0.0.0:80 app:app`

**Comment by pgjones** [comment]
@marodev reloading isn't supported with multiple workers. Reloading is a development feature, whereas multiple workers is a production feature so I haven't seen a need for them to work together.

**Comment by marodev** [comment]
@pgjones I should have been more precise. I was wondering if hypercorn works with multiple workers on Windows or if that feature is only supported on Unix. That’s why I didn’t provide the reload flag in my example.

**Comment by pgjones** [comment]
I see, it should work. If it isn't it would be good to see any errors (or why you think it isn't).
