### ISSUE TITLE
Hypercorn 0.15.0 failing in Python 3.7.17

### ISSUE THREAD

**Issue by userAman16** [pgjones/hypercorn#165]
hi imported package [quart](https://pypi.org/project/Quart/0.14.1/) 
and internally quart is importing package Hypercorn 0.15.0
on Python 3.7.17
getting below error

`File "/home/venv3/lib/python3.7/site-packages/quart/__init__.py", line 6, in <module>
    from .app import Quart
  File "/home/venv3/lib/python3.7/site-packages/quart/app.py", line 32, in <module>
    from hypercorn.asyncio import serve
  File "/home/venv3/lib/python3.7/site-packages/hypercorn/asyncio/__init__.py", line 4, in <module>
    from typing import Awaitable, Callable, Literal, Optional
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
`
reference [https://stackoverflow.com/a/61206514/8409759](https://stackoverflow.com/a/61206514/8409759)

**Comment by vikroxx** [comment]
Yes, I am also getting the same error. Were you able to find a fix?

**Comment by userAman16** [comment]
Workaround, had to downgrade hypercorn which uses correct package of quart.

**Comment by pgjones** [comment]
Python 3.7 has reached end of life and is no longer supported.
