### ISSUE TITLE
Support for add_middleware()

### ISSUE THREAD

**Issue by gellnerm** [pgjones/hypercorn#179]
Thank you for making hypercorn.

As per the fastapi [documentation](https://fastapi.tiangolo.com/advanced/middleware/) the recommended way to add a middleware is to use

`app.add_middleware(Middleware)`

However, this does not work, at least for the _ProxyFixMiddleware_. When used this way, this is the exception stack when making a request:

> [2024-01-02 12:42:02 +0100] [36653] [ERROR] Error in ASGI Framework
> Traceback (most recent call last):
>   File "lib/python3.11/site-packages/hypercorn/asyncio/task_group.py", line 27, in _handle
>     await app(scope, receive, send, sync_spawn, call_soon)
>   File "lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 34, in __call__
>     await self.app(scope, receive, send)
>   File "lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
>     await super().__call__(scope, receive, send)
>   File "lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
>     raise exc
>   File "lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "lib/python3.11/site-packages/hypercorn/middleware/proxy_fix.py", line 22, in __call__
>     scope = deepcopy(scope)
>             ^^^^^^^^^^^^^^^
>   File "lib/python3.11/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
>         ^^^^^^^^^^^^^^^
>   File "lib/python3.11/copy.py", line 231, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>                              ^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/copy.py", line 271, in _reconstruct
>     state = deepcopy(state, memo)
>             ^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
>         ^^^^^^^^^^^^^^^
>   File "lib/python3.11/copy.py", line 231, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>                              ^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/copy.py", line 272, in _reconstruct
>     if hasattr(y, '__setstate__'):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/site-packages/starlette/datastructures.py", line 702, in __getattr__
>     return self._state[key]
>            ^^^^^^^^^^^
>   File "lib/python3.11/site-packages/starlette/datastructures.py", line 702, in __getattr__
>     return self._state[key]
>            ^^^^^^^^^^^
>   File "lib/python3.11/site-packages/starlette/datastructures.py", line 702, in __getattr__
>     return self._state[key]
>            ^^^^^^^^^^^
>   [Previous line repeated 959 more times]
>   File "lib/python3.11/site-packages/starlette/datastructures.py", line 700, in __getattr__
>     def __getattr__(self, key: typing.Any) -> typing.Any:
>     
>   File "lib/python3.11/site-packages/starlette/datastructures.py", line 700, in __getattr__
>     def __getattr__(self, key: typing.Any) -> typing.Any:
>     
> RecursionError: maximum recursion depth exceeded
> 

Minimal example:

```
import asyncio

from fastapi import FastAPI, Request
from hypercorn.asyncio import serve
from hypercorn.config import Config
from hypercorn.middleware import ProxyFixMiddleware

app = FastAPI()
app.add_middleware(ProxyFixMiddleware, mode='modern', trusted_hops=1)

@app.get('/test1/{test}')
def test1(request: Request, test: str):  # @UnusedVariable
    return {'dd': 1}


if __name__ == '__main__':
    config = Config()
    config.bind = ['127.0.0.1:8000', '[::1]:8000']
    asyncio.run(serve(app, config))
```

**Comment by pgjones** [comment]
@kludex I think Starlette is doing the wrong thing here as per https://github.com/django/asgiref/issues/343, what do you think?

**Comment by Kludex** [comment]
I did fix that on the last release: https://github.com/encode/starlette/pull/2352. What Starlette version is being used here?

Also, kind a related, it would be cool if you can check https://github.com/django/asgiref/issues/424. 🙏

**Comment by gellnerm** [comment]
> What Starlette version is being used here?

0.27.0

**Comment by pgjones** [comment]
Should be fixed now given enough time has passed for release updates.

**Comment by dragoangel** [comment]
@pgjones well for me this still the case with `python:3.10-slim` and next `requirements.txt`:
```
hypercorn~=0.16
starlette~=0.37.0
```

**Comment by pgjones** [comment]
This is likely a bug with the `ProxyFixMiddleware` that is fixed in 0.17.0, just released.

**Comment by dragoangel** [comment]
Just rebuild with `hypercorn~=0.16` and still issue is same:
```
[2024-05-27 20:06:27 +0000] [13] [ERROR] Error in ASGI Framework
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/usr/local/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette_exporter/middleware.py", line 285, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/asgi_correlation_id/middleware.py", line 90, in __call__
    await self.app(scope, receive, handle_outgoing_request)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/hypercorn/middleware/proxy_fix.py", line 23, in __call__
    scope = deepcopy(scope)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 272, in _reconstruct
    if hasattr(y, '__setstate__'):
  File "/usr/local/lib/python3.10/site-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/site-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/site-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  [Previous line repeated 966 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by dragoangel** [comment]
Can you please re-open issue as it not yet solved?

**Comment by markhobson** [comment]
I'm also experiencing this error with Hypercorn 0.18.0 and Starlette 0.50.0.

Does the problem lie with the Hypercorn middleware or the way Starlette is integrating it?

**Comment by Aonodensetsu** [comment]
[starlette adds app to scope](https://github.com/Kludex/starlette/blob/f14480e13c041b51043072143c6fd3c7c8a1abbe/starlette/applications.py#L87), and [hypercorn deepcopies the scope](https://github.com/pgjones/hypercorn/blob/main/src/hypercorn/middleware/proxy_fix.py#L24), which includes the app, which includes middleware which includes the app (i think)

deepcopy should handle recursion but for some reason it doesn't here, the fix is shallow copying, which is incorrect from an asgi perspective since scope shouldn't be mutated, app isn't modified so shallow copying *it* is fine, the other attributes don't cause issues

`scope = {k: deepcopy(v) if k != "app" else v for k, v in scope.items()}`
