### ISSUE TITLE
Feture request - serve on random free open port

### ISSUE THREAD

**Issue by GoodDingo** [pgjones/hypercorn#19]
I need the functionality (for CI/CD integration tests) to serve quart application on random free port.

When run with `--bind 127.0.0.1:0` it serves stuff on port `0` whatever that means...

    Running on 127.0.0.1:0 over http (CTRL + C to quit)

----

 It'd be great to modify this functionality to standard python behaviour like in: 

    python -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()'

**Comment by pgjones** [comment]
I think this is a bug, I'll look to fix.

**Comment by pgjones** [comment]
The bug is that Hypercorn does serve on a random free port, but doesn't state which port in the output.

**Comment by pgjones** [comment]
This is fixed in 1df1c27f25461f17a14edeb0d60b2460a2fa12d3, please reopen if not :).

**Comment by GoodDingo** [comment]
Thanks Phil, I’ll verify later. 

P.S.
Big fan of Quart, good job! Appreciate your work...
