### ISSUE TITLE
Should Hypercorn be proxied behind nginx?

### ISSUE THREAD

**Issue by jtschoonhoven** [pgjones/hypercorn#193]
Hello, I've recently switched from using gunicorn+flask to hypercorn+quart. The gunicorn docs make it clear that gunicorn should always be proxied behind nginx. The hypercorn docs don't currently make this recommendation.

Should hypercorn be proxied behind nginx?

**Comment by pgjones** [comment]
I prefer not to, as nginx will terminate HTTP/2 (and possibly HTTP/3) whereas I'd like Hypercorn to do so. However, there is no reason not to if you'd prefer nginx as the public facing server.

I think the Gunicorn docs recommend this as the default Gunicorn worker is not async, and hence can't handle concurrent requests as nginx does (by queuing).
