### ISSUE TITLE
[Question] multiple workers with a resource-constrained app

### ISSUE THREAD

**Issue by lmeyerov** [pgjones/hypercorn#20]
We have a `Quart` server fronting some slow resource-constrained tasks (10ms-10s).  Ideally, we have a `quart` instance per resource and `hypercorn` does a fair (or at least round-robin) dispatch across them. I know how to do this w/ Celery, as it naturally handles tasks, or redesigning to a more REST-ful put task / get status design, but I'm unclear w/ simple `hypercorn` + `quart` approach. If we had `-w 20 ./my_quart_singleton.sh` (for 20 resources), would that spawn 20 `quarts`, or some other path here?

**Comment by pgjones** [comment]
Each Hypercorn worker is a separate process; I'm not sure how the requests are dispatched to them though (they all listen to the same socket, so maybe the os decides?). You could consider `asyncio.run_in_executor` with a process pool for this though.
