### ISSUE TITLE
How do I log username in access log?

### ISSUE THREAD

**Issue by nabheet** [pgjones/hypercorn#230]
I have a Fast API application that uses Bearer tokens. Is there was way for me to provide hypercorn the username or some identifier of the user/service-account associated with the bearer token from Fast API? So that it can be logged in the access log.

EDIT 1: I just realized I could set a response header in fast api and have hypercorn log it in the access log. Is that the best way to accomplish this?

**Comment by pgjones** [comment]
I think the response header would work. Although it might make more sense to access log in FastAPI rather than Hypercorn - there is a good discussion of options [here](https://stackoverflow.com/questions/69670125/how-to-log-raw-http-request-response-in-python-fastapi/73464007#73464007)
