### ISSUE TITLE
Can we please get a new release?

### ISSUE THREAD

**Issue by nabheet** [pgjones/hypercorn#236]
I would love to get the bug fix for preventing duplicate access log events. https://github.com/pgjones/hypercorn/issues/158

And hopefully a fix for the weird HTTP/2 exception: https://github.com/pgjones/hypercorn/issues/197. It just pollutes our logs with errors and is preventing us from using HTTP/2.

Thank you!

**Comment by pgjones** [comment]
0.17.0 released
