### ISSUE TITLE
@app.before_serving does not start in kubernetes

### ISSUE THREAD

**Issue by gattytto** [pgjones/hypercorn#268]
Hello everyone

my setup is pretty trivial and it works when I run it locally, it's just a python script that has an async function  decorated with @app.before_serving 

the app is ran using the usual "hypercorn --bind [::]:8000 --workers 1 -k asyncio filename:app"
if I run this command locally in my computer or the LXC container that I'm using for dev it works just fine but when I run the app in a kubernetes deployment the command results in the hypercorn+quart app not running the function decorated with @app.before_serving.

the app also works if I do "kubectl exec -it pod-name -c container-name -- bash" and then run the hypercorn command inside the interactive terminal.

I've tried creating an entrypoint file inside the container with the hypercorn command inside it and running it directly in the "command" property of the pod spec but it still does not work. 

is this a limitation in kubernetes design or runc runtime?, I couldn't find any result in google for someone having the same issue with this kind of usecase.

I'll appreciate any input about this.

I also don't see any error or exception being thrown by the app, it just seems to ignore the decorated function.

it kind of looks like this:
```python
from quart import Quart
import asyncio

async def create_client():
    conn=await create-some-other-client-connection()

app = Quart(__name__)
async def loop_stream_cli():
    while True:
         print('test')
         await do-something-with-the-client-connection()
         await asyncio.sleep(1)

@app.before_serving
async def unlink_stream_cli():
    print('unlink stream cli')
    if "KUBERNETES_PORT" in os.environ.keys():
        kubeConfig.load_incluster_config()
        print('loaded in_cluster config')
    await create_client()
    loop=asyncio.get_running_loop()
    loop.create_task(loop_stream_cli())

```

**Comment by roys10** [comment]
The @app.before_serving doesn't work, but is the webserver up? If so do other functions work?
