### ISSUE TITLE
A bit of Hypercorn history

### ISSUE THREAD

**Issue by kaldown** [pgjones/hypercorn#30]
Hi.

As the README.md says:

> Hypercorn was initially part of Quart before being separated out into a standalone ASGI server. Hypercorn forked from version 0.5.0 of Quart.

Sorry for asking. 
If this is not a political decision - could you please tell then, why you forked from Quart, being one of the contributor?
Is that something with the new approach, technology, or just to sharpen your skill?

Wonder if there is a milestone with the design architecture, which easier to be solved as a fork.

Thank you.

**Comment by pgjones** [comment]
When I started Quart in 2017 the common practice was to build a framework that included the server (unlike WSGI frameworks), for example aiohttp and Sanic. Indeed Sanic was popularized on the speed of its inbuilt server. In 2018 I was introduced to ASGI, and felt it made a lot of sense so I split the then Quart into an ASGI server Hypercorn, and ASGI framework (today's) Quart.

**Comment by kaldown** [comment]
Thank you for the explanation.
