### ISSUE TITLE
Invalid protocol process on h2c

### ISSUE THREAD

**Issue by songdongsheng** [pgjones/hypercorn#32]
When I use the latest hypercorn for h2c testing, I found only use uvloop in Docker desktop 2.3.0.3 for Windows works.

- trio, uvloop and asyncio on Debian Linux 10/11 not works
- trio and asyncio on Windows 10 not works.

**Comment by songdongsheng** [comment]
[h2c-prior-knowledge.zip](https://github.com/pgjones/hypercorn/files/4779571/h2c-prior-knowledge.zip)

- h2c-prior-knowledge-ok-uv.pcap
- h2c-prior-knowledge-xx-aio.pcap

From the pcap files, it seems that hypercorn  send a extra SETTINGS to the client, then waiting, didn't send DATA anymore.

*Magic (PRI) -> server
*SETTINGS (0) -> server
*WINDOW_UPDATE (0) -> server
*HEADERS (1) -> server
*SETTINGS (0) -> client
*SETTINGS (0) -> server
!SETTINGS (0) -> client [Extra]
*HEADERS (1) -> client
?DATA (1) -> client [none]

**Comment by pgjones** [comment]
I think this has been fixed in the latest release (I may have discussed this with you on gitlab). Please reopen if it isn't fixed.
