### ISSUE TITLE
Request freezes if I get throttled by an extra service

### ISSUE THREAD

**Issue by peasant98** [pgjones/hypercorn#35]
Hi @pgjones, I am currently using hypercorn with a Discord server that I created with quart. I have an a code excerpt that looks like this:

```py

@app.route("/create_invite", methods=['GET'])
async def create_invite():
    """
    create an invite for the guild.
    """
    # wait_until_ready and check for valid connection is missing here
    guilds = client.guilds
    guild = guilds[0]
    link_str = 'n/a'
    for channel in guild.channels:
        if channel.name == 'general':
            print('creating invite')
            link = await channel.create_invite()
            link_str = str(link)
            break
    return jsonify({'invite_link': link_str}), 200
```

However, I think after 5 requests (`link = await channel.create_invite()`), I get throttled. When I run `python main.py` normally, I have to wait a bit of extra time; but when I run with hypercorn, I have to wait indefinitely. How can I fix this?

**Comment by pgjones** [comment]
What do you mean by waiting in this case?

**Comment by peasant98** [comment]
Just blocks there

**Comment by peasant98** [comment]
Like if I'm making a request, it will just say "pending" forever.

**Comment by peasant98** [comment]
@pgjones

**Comment by pgjones** [comment]
How are you running it with Hypercorn? `python main.py` also runs Hypercorn, so it is hard to see why it will be stuck waiting one way over the other.

**Comment by peasant98** [comment]
`python main.py` won't run hypercorn if I don't explicitly import it though, right?

**Comment by pgjones** [comment]
What are the two ways you run it? You said there was one with hypercorn which I assume is `hypercorn main:app` and one without which I assume is `python main.py` - is this the case? 

If running `python main.py` uses `app.run()` then you will be using Hypercorn (Quart is not able to serve itself).

**Comment by peasant98** [comment]
Forgot to respond, I found a workaround.
