### ISSUE TITLE
Setting config.alpn_protocols has no impact when disabling http/1.1

### ISSUE THREAD

**Issue by aziz142010** [pgjones/hypercorn#38]
I am trying to run Hypercorn server with FastAPI by disabling http/1.1. Setting the alpn_protocols value to *h2* only has no impact and the server still serves http/1.1 requests.
Is there anything else we need to change to disable serving http/1.1 ??

```
from hypercorn.config import Config,serve

config = Config()
# Setting the protocol to http2 only !!
config.alpn_protocols = ["h2"]

server_task = loop.create_task(
                                serve(ins_server.app, config)
                            )
...
```

**Comment by pgjones** [comment]
This would stop the server advertising h11, but it will still respond to h11 requests. Are you wanting the server to ignore h11 requests?

**Comment by aziz142010** [comment]
We had a request where we had to support only http2 and ignore h11 requests. I was under the assumption that I will be able to serve only http2 requests with this configuration.

**Comment by pgjones** [comment]
There is only an ability to not advertise a protocol, Hypercorn will still respond if used.
