### ISSUE TITLE
Is it possible to Programmatically figure out the bind address of the running hypercorn server ? 

### ISSUE THREAD

**Issue by aziz142010** [pgjones/hypercorn#39]
I have started the Hypercorn server using the serve api. Is there any way to figure out programmatically as to which address the Hypercorn server is bonded ?? And also can we get the config details of the running Hypercorn Webserver ??

```
http://127.0.0.1:8080 
```

**Comment by pgjones** [comment]
It is available as part of the `server` key passed as part of the asgi scope
