### ISSUE TITLE
ImportError: cannot import name 'LifespanFailure' from 'hypercorn.utils'

### ISSUE THREAD

**Issue by adam-pawluczuk** [pgjones/hypercorn#45]
Hello.

After automatically upgrading to the newest version (`0.12.0`):

```python
ImportError: cannot import name 'LifespanFailure' from 'hypercorn.utils'
```

I can see that in `0.12.0` `LifespanFailure` was renamed to `LifespanFailureError` (along with other renamings).

Is `0.12.0` considered to have breaking changes?

Thank you!
Adam

**Comment by pgjones** [comment]
I didn't think `LifespanFailure` would be used outside of the Hypercorn code directly - I'd like to learn about your usage.

It is a renaming, I'll add it to the changelog.

**Comment by adam-pawluczuk** [comment]
So basically what I have is this:

```
from hypercorn.utils import LifespanFailure

try:
    await self.app(scope, receive, send)
except LifespanFailure:
    pass
```

It is being used like this in one of the middlewares.

**Comment by pgjones** [comment]
I'm not sure that these errors should leak out to the middleware - I guess this is an app that doesn't support lifespans?

**Comment by adam-pawluczuk** [comment]
Yes, that makes sense. So it looks like it could be the fault on the application side then. Thank you!

**Comment by pgjones** [comment]
Thinking about this some more, I think the specification allows for any Exception subclass to be raised - so I don't think your middleware should rely on it being a LifespanFailureError.
