### ISSUE TITLE
Add support for certiciate file protected by a password

### ISSUE THREAD

**Issue by adam-pawluczuk** [pgjones/hypercorn#46]
As I understand `hypercorn` does not support providing a password for encrypted private certificate key:

https://github.com/pgjones/hypercorn/blob/0.12.0/src/hypercorn/config.py#L168

Would be nice add the support.

Looks like this is an easy change.

**Comment by pgjones** [comment]
Done in eba651c81e198b49f60914074628c19e9193a287

**Comment by adam-pawluczuk** [comment]
Wow that was really fast.

Thank you, really appreciate that!
