### ISSUE TITLE
How to make file upload?

### ISSUE THREAD

**Issue by joaopedrolourencoaffonso** [pgjones/hypercorn#47]
I'm having difficulty finding a working example of uploading files. How can I get the file **content**? Or at least the file path?
```python
@app.route('/arquivo', methods=['POST'])
async def upload_file():
    x = await request.get_data();
    x = x.decode("utf-8") 
    print(x);
```
The only thing this code get's me is the file name, but neither it's  path nor it's content. Can you point me to a working example? It doesn't need to have security or anything else, I just want to compreehend the basics.

**Comment by pgjones** [comment]
There is good documentation [here](https://flask.palletsprojects.com/en/2.0.x/patterns/fileuploads/). To use this with Quart change `request.files` to `(await request.files)` (and Flask with Quart).

```python
@app.route('/arquivo', methods=['POST'])
async def upload_file():
    x = await request.files
    file = x['file']
    print(file.filename)
    ...
```
