### ISSUE TITLE
restart does not work on Windows with spaces in path

### ISSUE THREAD

**Issue by slokhorst** [pgjones/hypercorn#49]
I'm using Quart on Windows and I want to use the auto-reload function. When it detects changes and attempts to restart, I get the following:

```
PS: can't open file 'C:\\Users\\Sebastiaan Lokhorst\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe': [Errno 2] No such file or directory
```

Apparently, this is caused by Windows weirdness with spaces, see e.g. https://bugs.python.org/issue19066 and https://bugs.python.org/issue436259

I tried to mess around with all kinds of combinations with quotes and backslashes, to no success. What **did** help, as suggested in the bug report: "just use subprocess instead":

If I replace [this line](https://github.com/pgjones/hypercorn/blob/2c73502f40d5c4159fe4c4cedfba43272cf7d8cd/src/hypercorn/utils.py#L194):
```python
os.execv(executable, [executable] + args)
```

with this line:
```python
import subprocess
subprocess.run([executable] + args)
```

It works great! (only tested on Windows, not Linux)

I don't know if there are any subtile differences between `os.execv` and `subprocess.run` though, so it might or might not be a universal fix.

Edit: One of the downsides is that subprocess starts a new process instead of replacing the old one. So after 20 restarts you have 20 processes.

Setup:
* Windows 10 21H2 (x64)
* Python 3.10 (Microsoft Store version)
* quart 0.16.2
* hypercorn 0.13.2

**Comment by pgjones** [comment]
Should be fixed with 67ff9c974f781e33965fe887af6b01810974d69e, please reopen if not.
