### ISSUE TITLE
Question: Get worker number from within worker?

### ISSUE THREAD

**Issue by lmeyerov** [pgjones/hypercorn#54]
Is there a way for a worker to know which # worker it is? In other systems, it is common to have an environment variable (`WORKER=0`, ...), but I didn't see anything
 
We're trying to match the CPU + GPU NUMA hierarchy for our workers, and are currently launching our Quart workers as `hypercorn -b 0.0.0.0:$PORT --worker-class uvloop ...` .

**Comment by pgjones** [comment]
Does this work?
```python
import os
print(os.getpid())
```

**Comment by lmeyerov** [comment]
No, that is the pid

**Comment by lmeyerov** [comment]
Thanks -- I saw this is marked closed as "completed", though am not finding it in the docs or closed PRs, is there a feature implementing this I should be looking for?

**Comment by pgjones** [comment]
Each Hypercorn worker is a process so the pid can be used to identify which worker at runtime.

**Comment by lmeyerov** [comment]
When we launch N workers, we cannot tell which 1 of N, eg, leader. It's fine not implementing, thanks for the clarification.

**Comment by lmeyerov** [comment]
This isn't about what hypercorn needs but the software on top. In our case, it helps to know the worker number and count.
