### ISSUE TITLE
h11_max_incomplete_size marked as HTTP/2 in documentation

### ISSUE THREAD

**Issue by touilleMan** [pgjones/hypercorn#58]
[In the documentation](https://github.com/pgjones/hypercorn/blob/8cef567301a5a3f4363d1c2cad76008e58add8aa/docs/how_to_guides/configuring.rst):
![image](https://user-images.githubusercontent.com/3187637/173015850-fc91c538-0bd5-4805-8e11-1992b2490e37.png)

However `h11_max_incomplete_size ` is used in h11 (so HTTP 1.1 support):
https://github.com/pgjones/hypercorn/blob/8cef567301a5a3f4363d1c2cad76008e58add8aa/src/hypercorn/protocol/h11.py#L96

**Comment by touilleMan** [comment]
Also it would be good to document the default values for the various limits in the documentation, cf. https://github.com/pgjones/hypercorn/blob/8cef567301a5a3f4363d1c2cad76008e58add8aa/src/hypercorn/config.py#L75-L78

Would you accept a PR on this ?

**Comment by pgjones** [comment]
I'd very much welcome PRs on these
