### ISSUE TITLE
HTTPStream.app_send is missing http.disconnect handling ?

### ISSUE THREAD

**Issue by touilleMan** [pgjones/hypercorn#59]
## tl;dr

I don't see the code responsible for handling `http.disconnect` in http stream:
https://github.com/pgjones/hypercorn/blob/8cef567301a5a3f4363d1c2cad76008e58add8aa/src/hypercorn/protocol/http_stream.py#L117-L177

It looks like an omission to me, especially given the websocket stream has code for handling it corresponding `websocket.close`

## Long versions

I've written a simple middleware to simulate the asgi app being not responsive:

```python
class AsgiOfflineMiddleware:

    def __init__(self, asgi_app):
        self.asgi_app = asgi_app
        self._offline_ports = set()
        self._offline_watchdogs_parking = trio.lowlevel.ParkingLot()

    @contextmanager
    def offline(self, port: int):
        assert port not in self._offline_ports
        self._offline_ports.add(port)
        self._offline_watchdogs_parking.unpark_all()
        try:
            yield
        finally:
            self._offline_ports.remove(port)
            # No need to unpark given our port has just been re-authorized !

    async def __call__(self, scope, receive, send):
        # Special case for lifespan given it corresponds to server init and not
        # to an incoming client connection
        if scope["type"] == "lifespan":
            return await self.asgi_app(scope, receive, send)

        port = scope["server"][1]

        pretend_to_be_offline = False

        if port in self._offline_ports:
            pretend_to_be_offline = True

        else:

            async def _offline_watchdog(cancel_scope):
                nonlocal pretend_to_be_offline
                while True:
                    await self._offline_watchdogs_parking.park()
                    if port in self._offline_ports:
                        break
                pretend_to_be_offline = True
                cancel_scope.cancel()

            async with trio.open_nursery() as nursery:
                nursery.start_soon(_offline_watchdog, nursery.cancel_scope)
                await self.asgi_app(scope, receive, send)
                nursery.cancel_scope.cancel()

        if pretend_to_be_offline:
            if scope["type"] == "http":
                await send({"type": "http.disconnect"})
            elif scope["type"] == "websocket":
                await send({"type": "websocket.close"})
            else:
                assert False, scope
```

However it produce errors when trying to close an HTTP connection:

```
ERROR    hypercorn.error:logging.py:100 Error in ASGI Framework
Traceback (most recent call last):
  File "C:\Users\gbleu\source\repos\parsec-cloud\venv39\lib\site-packages\hypercorn\trio\task_group.py", line 21, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "C:\Users\gbleu\source\repos\parsec-cloud\venv39\lib\site-packages\hypercorn\utils.py", line 247, in invoke_asgi
    await app(scope, receive, send)
  File "C:\Users\gbleu\source\repos\parsec-cloud\parsec-cloud\tests\common\backend.py", line 427, in __call__
    await send({"type": "http.disconnect"})
  File "C:\Users\gbleu\source\repos\parsec-cloud\venv39\lib\site-packages\hypercorn\protocol\http_stream.py", line 177, in app_send
    raise UnexpectedMessageError(self.state, message["type"])
hypercorn.utils.UnexpectedMessageError: Unexpected message type, http.disconnect given the state ASGIHTTPState.REQUEST
```

**Comment by synodriver** [comment]
Hi. According to the [spec](https://asgi.readthedocs.io/en/latest/specs/www.html), ```http.disconnect``` is an asgi receive event instead of send event, so you can not close the http connection in that way. Return 500 error would be ok.

**Comment by touilleMan** [comment]
@synodriver Ho you're right ! I read the spec a bit too fast ^^

> It looks like an omission to me, especially given the websocket stream has code for handling it corresponding websocket.close

So `websocket.disconnect` is also an event send *to* the application, hence wasn't hypercorn supposed to have raise an `hypercorn.utils.UnexpectedMessageError` when my application sent a `websocket.disconnect` to the server ?

**Comment by synodriver** [comment]
You can send ```websocket.close``` which is listed in asgi spec.
> Close - send event
Sent by the application to tell the server to close the connection.

> If this is sent before the socket is accepted, the server must close the connection with a HTTP 403 error code (Forbidden), and not complete the WebSocket handshake; this may present on some browsers as a different WebSocket error code (such as 1006, Abnormal Closure).

> If this is sent after the socket is accepted, the server must close the socket with the close code passed in the message (or 1000 if none is specified).

> type (Unicode string) – "websocket.close".
code (int) – The WebSocket close code, as per the WebSocket spec. Optional; if missing defaults to 1000.
reason (Unicode string) – A reason given for the closure, can be any string. Optional; if missing or None default is empty string.

**Comment by synodriver** [comment]
> So `websocket.disconnect` is also an event send _to_ the application, hence wasn't hypercorn supposed to have raise an `hypercorn.utils.UnexpectedMessageError` when my application sent a `websocket.disconnect` to the server ?

Actually hypercorn did it [here](https://github.com/pgjones/hypercorn/blob/main/src/hypercorn/protocol/ws_stream.py#L299)

**Comment by touilleMan** [comment]
thanks a lot @synodriver 😃 🎉 

so it's `websocket.close` that is the event the application send, and `websocket.disconnect` (and `http.disconnect`) that are send *to* the application !
