### ISSUE TITLE
Doesn't serve HTTP/3 over QUIC from Chrome borwser

### ISSUE THREAD

**Issue by anthonyyuan** [pgjones/hypercorn#60]
hi :
    I alsoe meet this problem

**Comment by synodriver** [comment]
You need a proper http certificate to make it work... Or the browser will refuse to send any request

**Comment by pgjones** [comment]
https://pgjones.dev works over HTTP/3, so this is in general working. I think you need to serve over HTTP/1 or HTTP/2 with an Alt-Svc header for chrome to switch to HTTP/3 (rather than connect directly).
