### ISSUE TITLE
`config.access_logger_class` mentionned in the documentation but doesn't exists

### ISSUE THREAD

**Issue by touilleMan** [pgjones/hypercorn#61]
[The documentation](
https://pgjones.gitlab.io/hypercorn/how_to_guides/logging.html#customising-the-access-logger) mentions customization `config.access_logger_class`, however this attribute doesn't exists in the configuration and neither the `hypercorn.logging.AccessLogger` class

**Comment by pgjones** [comment]
Updated in 05f70202faa5eab9d19f0d401b2e4da3ffdbd9ba
