### ISSUE TITLE
No ASGI version in lifespan scope (0.14.1)

### ISSUE THREAD

**Issue by vytas7** [pgjones/hypercorn#65]
According to [Falcon's CI](https://github.com/falconry/falcon/runs/8085298888?check_suite_focus=true#step:6:5423), it seems that things stopped working with the recently released Hypercorn 0.14.0 and 0.14.1.

This is how ASGI scope looks like in Uvicorn and Hypercorn 0.13.2:
```python
{'type': 'lifespan', 'asgi': {'spec_version': '2.0', 'version': '3.0'}}
```
This is how it looks in Hypercorn 0.14.1:
```python
{'type': 'lifespan', 'asgi': {'spec_version': '2.0'}}
```

The [spec reads](https://asgi.readthedocs.io/en/latest/specs/main.html#specification-details):
> The key `scope["asgi"]` will also be present as a dictionary containing a `scope["asgi"]["version"]` key that corresponds to the ASGI version the server implements. If missing, the version should default to `"2.0"`.

According to the spec, Falcon treats the missing version as 2.0, and fails startup since that calling style is unsupported.

Is there any specific reason for omitting the ASGI version in 0.14.x?

**Comment by pgjones** [comment]
Thanks, this is fixed in 4ae32dfd964638102f5f6bfa2eee44af2254a747 and was missed when ASGI 2 support was dropped. I'll wait a couple of days for any other bugs then release.
