### ISSUE TITLE
Can no longer access raw headers for HTTP1.1 

### ISSUE THREAD

**Issue by thrau** [pgjones/hypercorn#66]
With hypercorn 0.13.2, the h11 headers that were available in the ASGI `scope['headers']`, was a `Headers` object that allowed access to the raw headers that preserved the casing of headers as the client provided them.

The following commit  introduced a change, where the h11 Headers object were cast into a list, from which the original header casing can no longer be restored. https://github.com/pgjones/hypercorn/commit/058e84f5cb418fca40cabc991d40c87dfc44a39e#diff-557b56f90870312d8cdaa478f71feca14d4fee5047385d1a4d6b152bdacddc4cR222

It's clear to me that HTTP headers should be case insensitive, however, clients often expect headers in a certain casing regardless, and when using hypercorn as a proxy, it would be great if there was a way to preserve the original header casing from the client request.

Was there a particular reason to convert the raw headers to a list, and no longer use the `Headers` object? Would there be some other way we could preserve the original request headers?

### Example

This app:
```python
from quart import Quart, request, jsonify

app = Quart(__name__)


@app.route("/", methods=["GET"])
async def echo_headers():
    items = request.scope.get("headers").raw_items()

    return jsonify([(k.decode('utf-8'), v.decode('utf-8')) for k, v in items])


def main():
    app.run()


if __name__ == '__main__':
    main()
```

would return something like:
```
 % curl -s -H 'x-foo-bar: value' localhost:5000 | jq .
[
  [
    "Host",
    "localhost:5000"
  ],
  [
    "User-Agent",
    "curl/7.68.0"
  ],
  [
    "Accept",
    "*/*"
  ],
  [
    "x-foo-bar",
    "value"
  ]
]
```

**Comment by pgjones** [comment]
The `Headers` object was never meant to be passed in the scope (as it doesn't conform to the ASGI specification). However, I agree the raw casing (for HTTP/1) should be preserved. See 44cfda145a46bd4ca849e49cb111d2b6e9f2e185
