### ISSUE TITLE
How to run a zip?

### ISSUE THREAD

**Issue by dimaqq** [pgjones/hypercorn#7]
I'm developing with hypercorn and quart. I've set up my code as a package (to benefit from intra-package imports), and thus I can run it from source as:
* python -m mypackage
* env QUART_APP=mypackage.__main__ quart run  # slightly ugly __main__ because top-level is a package.
* hypercorn --worker-class uvloop mypackage.__main__

Now I'm ready to package my code, and I'm thinking a zip archive, which would allow me to do the following with some tweaks:
* python mypackage.zip
* env PYTHONPATH=./mypackage.zip hypercorn mypackage.__main__ . # works, but kinda ugly...
* hypercorn [some flag?] mypckage.zip # doesn't work, I think there's no provision for that

Am I missing something?
Is there a recommended way of doing this?
Is this a good/bad idea?

P.S. in case someone wonders about depenencies, I'm using pipenv/Pipfile for running from source and I install depenencies into a docker image as a separate step for production.

**Comment by pgjones** [comment]
Is this a common way of packaging things? I don't think I've seen it before. I tend to just run `pip install -r requirements.txt` in the docker image, as [explained here](https://smarketshq.com/smarkets-dockerfiles-ea59ad75ebaa).

**Comment by dimaqq** [comment]
Well, perhaps not that common after all. I guess in the end why I like zip archives and zipimport is that it's possible to make a reproducible snapshot of the repository (with a few flags to strip timestamps and ensuring canonical file order), thus a repo hash can be mapped to zip hash. But then again that's not all that different from an image layer hash (with similar provisions).

The rest is just like in your article, first there's Python base image, then there's a layer that contains all the dependencies, and finally there's a layer with app code.
