### ISSUE TITLE
Stream WSGI responses?

### ISSUE THREAD

**Issue by pgjones** [pgjones/hypercorn#76]

**Comment by synodriver** [comment]
Acctually [a2wsgi](https://github.com/abersheeran/a2wsgi) did that well.

**Comment by thrau** [comment]
I guess there's a million ways to solve this. I built this for LocalStack where we stream responses through Werkzeug by passing an iterator to the `response` attribute of the Werkzeug Response object. In our asgi/wsgi bridge, the `ASGISendCallable` is exposed as the wsgi send response protocol with [an adapter class](https://github.com/localstack/localstack/blob/master/localstack/http/asgi.py#L241). The low level thing to make that work is wrapping a synchronous iterator as an asyn generator, [here](https://github.com/localstack/localstack/blob/master/localstack/http/asgi.py#L90).
Not sure whether this is what you're looking for 🤷

**Comment by pgjones** [comment]
See d5aa25e59c920ffb154499e25eb9bf625c3ddf45
