### ISSUE TITLE
HTTP Basic authentication issue with FastAPI

### ISSUE THREAD

**Issue by jrversteegh** [pgjones/hypercorn#77]
FastAPI HTTPBasic authentication appears to break when moving from hypercorn 0.14.1 to 0.14.2.

The HTTPBasic example from FastAPI:
```python
from fastapi import Depends, FastAPI
from fastapi.security import HTTPBasic, HTTPBasicCredentials
  
app = FastAPI()

security = HTTPBasic()


@app.get("/users/me")
def read_current_user(credentials: HTTPBasicCredentials = Depends(security)):
    return {"username": credentials.username, "password": credentials.password}
```
works well with 0.14.1, i.e. status 200 is returned with the authenticating user, but with 0.14.2 status 401 is returned even when credentials are provided, ending you up in a login dialog loop.
FastAPI version is 0.81.0

**Comment by synodriver** [comment]
Hi, this is introduced in [this](https://github.com/pgjones/hypercorn/commit/44cfda145a46bd4ca849e49cb111d2b6e9f2e185) commit, but I don't think it's hypercorn's bug. According to [asgi spec](https://github.com/pgjones/hypercorn/commit/44cfda145a46bd4ca849e49cb111d2b6e9f2e185),
> Header names should be lowercased, but it is not required; servers should preserve header case on a best-effort basis.

So, asgi frameworks are responsible to check the headers. Obviously, starlette did not, and fastapi didn't either.

**Comment by synodriver** [comment]
# Referrences: 

[fastapi's check](https://github.com/tiangolo/fastapi/blob/master/fastapi/security/http.py#L70)
> authorization: str = request.headers.get("Authorization")

[Starlette's check](https://github.com/encode/starlette/blob/master/starlette/datastructures.py#L555-L559)

```
def __getitem__(self, key: str) -> str:
        get_header_key = key.lower().encode("latin-1")
        for header_key, header_value in self._list:
            if header_key == get_header_key:
                return header_value.decode("latin-1")
        raise KeyError(key)
```

But this is what accually in the header
![image](https://user-images.githubusercontent.com/50922489/188313724-dec0e03f-e6ca-4508-a0bd-1ee6f6cf1459.png)

So, fastapi always get None. I think starlette should fix this.

**Comment by synodriver** [comment]
Well, there is another [discussion](https://github.com/django/asgiref/issues/246) here. Looks like incomming headers should be lowercased, but response headers should be preserved. Hypercorn have already preserved response headers, so should [this](https://github.com/pgjones/hypercorn/commit/44cfda145a46bd4ca849e49cb111d2b6e9f2e185) be reverted?

**Comment by synodriver** [comment]
Before they make a fix, you can try:
```
class LowerHeaderMiddleware:
    def __init__(self, app):
        self.app = app

    def lower_headers(self, headers):
        new_header = []
        for k, v in headers:
            new_header.append((k.lower(), v))
        return new_header

    async def __call__(self, scope, receive, send):
        if scope.get("headers"):
            scope["headers"] = self.lower_headers(scope["headers"])
            await self.app(scope, receive, send)
            return
        await self.app(scope, receive, send)

app.add_middleware(M)
```

This should work.

**Comment by pgjones** [comment]
Yea, reverted in 68e832af53b55bcd7798eac1e84c974eb5753827. @thrau I think we need to discuss on https://github.com/django/asgiref/issues/246

**Comment by pgjones** [comment]
Should now be fixed
