### ISSUE TITLE
Document (or fix?) dual stack bind option.

### ISSUE THREAD

**Issue by dimaqq** [pgjones/hypercorn#8]
I've discovered that the way to get hypercorn to listen to both IPv4 and IPv6 address on MacOS is:
*`hypercorn --bind ':::80' ...`  both IPv4 and IPv6

For example, following doesn't listen on both stacks:
* `hypercorn --bind 'localhost:80'`  instead it resolves `localhost` to just 1 address (IPv4 in my case).
* `hypercorn --bind '0.0.0.0:80'`  listens on IPv4 only
* `hypercorn --bind '[::]:80'` fails trying to resolve hostname `[::]` :(

Perhaps it's enough to document this?
I'm not sure what the common syntax for web frameworks, etc. is...

**Comment by pgjones** [comment]
I think it should be `hypercorn -b '0.0.0.0:5000' -b '[::]:5000' ...` but I've not yet added this functionality, I'll aim to do so soon.

**Comment by pgjones** [comment]
@dimaqq I've now added this in 2ca9750773e0045fd22cfea08262e49c45fed2a3, with documentation [here](https://pgjones.gitlab.io/hypercorn/binds.html). How does this look for you?

**Comment by dimaqq** [comment]
Perfect!

**Comment by pkit** [comment]
`hypercorn -b '0.0.0.0:5000' -b '[::]:5000' ...` 
this will fail on any modern Debian-based distro with `OSError: [Errno 98] Address already in use`
because `bindv6only` is false by default:
```
$ cat /proc/sys/net/ipv6/bindv6only
0
```
The correct behavior would be to use `IPV6_V6ONLY`: `s.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)` when both `--bind` arguments are used with the same port.

**Comment by dodysw3** [comment]
> The correct behavior would be to use `IPV6_V6ONLY`: `s.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)` when both `--bind` arguments are used with the same port.

@pkit currently I am having this issue, but doesn't understand your suggestion, is that a code change suggestion on hypercorn itself, or is it possible for client to monkey patch or do early initialization to allow the same port to be bounded to ipv4 and ipv6?

**Comment by pkit** [comment]
@dodysw3 It's the suggestion on how it should have been implemented in hypercorn.
Right now it just goes and binds both pairs one after another. Without checking if it needs to set `IPV6_V6ONLY` or not.
