### ISSUE TITLE
hypercorn eats SIGINTs, does not propagate KeyboardInterrupt/CancelledError

### ISSUE THREAD

**Issue by fastily** [pgjones/hypercorn#82]
The following program cannot be killed with a SIGINT (`ctrl`+`c`):

```python
import asyncio

from hypercorn.asyncio import serve
from hypercorn.config import Config
from starlette.applications import Starlette

async def web_ui():
    await serve(Starlette(), Config())

async def task():
    await asyncio.sleep(100000000000000)

async def main():
    await asyncio.gather(web_ui(), task())

if __name__ == "__main__":
    asyncio.run(main())
```

NB: This example uses [starlette](https://github.com/encode/starlette) as a dependency.

Hypercorn appears to be silently swallowing SIGINTs and does not propagate `KeyboardInterrupt` and/or `CancelledError` to force the program to exit.

Thanks for taking a look.

**Comment by pgjones** [comment]
Yep, when using the `serve` API it is important to add your own signal handlers and use the [`shutdown_trigger`](https://hypercorn.readthedocs.io/en/latest/how_to_guides/api_usage.html#graceful-shutdown). If you want Hypercorn to handle signals you should use the command line invocation.

(Note Starlette has background tasks for the `task`).
