### ISSUE TITLE
What if I want to share a variable among multiple workers?

### ISSUE THREAD

**Issue by T-baby** [pgjones/hypercorn#86]
For example, I have a multi-process queue and I want to share its use between the processes where these workers are located.

**Comment by T-baby** [comment]
I tried passing the multiprocessing.queue to the process when creating it and adding an attribute to app.app to get the multiprocessing.queue. Asynchronous communication across processes can be achieved if each process subscribes to this queue.

Maybe I should contribute a pr to hypercorn?

**Comment by pgjones** [comment]
There isn't a supported way to do this, and without ASGI support I wouldn't accept a PR. I'd recommend using a third party, such as redis to share this information or using the serve API and creating your own worker management system (as you may have don).
