### ISSUE TITLE
Simple "requests"-like get for http/3 server Example for Beginners

### ISSUE THREAD

**Issue by edwilsoncoutinho** [pgjones/hypercorn#95]
Hello, 

I'm a Python beginner and the API that I need to get data from is using h3(or HTTP/3) protocol to accept any request.

`hypercorn` and `aioquic ` seem to be the go-to libraries for a HTTP/3 client.

Would you kindly provide a simple implementation of a requests-like get? =)

**Comment by pgjones** [comment]
Hypercorn is a HTTP/3 server, so I can't give an example of a HTTP/3 client. 
There was a branch to httpx for HTTP/3 support, hopefully it will be revived.
